#!/usr/bin/env node

var CP = require('child_process');
var gitCachedFiles = CP.execSync('git diff --cached --name-only --diff-filter=ACMR').toString().trim();
var opts = {stdio: 'inherit'};

if (gitCachedFiles) {
    (process.platform === 'win32' ?
        CP.exec('npm test', opts) : CP.spawn('npm', ['test'], opts)).on('close', process.exit.bind(process));
}
